# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34408ffb4df0b1851737bb0801c23d9e5f20547f091daf541391971f104fcec3fef9fce0ae5c7fe0bd94e5e5a654484f00321c4982f3c39038e7d1af772f45f6

test:
  secret_key_base: 4e732a8b64ece84ff4749d2fe0be6ca5a0d8effb3a5b9b5280e9298937d49c82218723593bca9b59460e2e8879c9ac684b3d6a0388de47e0cece95239d90f2c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b60f406c26c7eef09ef102f712178b1c46e15942d526691d569a74e01ce09077d63a12a38d5c5bde2effde2ed9aa11b10fd9abdaad5f74de89338645e57c0574
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
